# Generated by Django 2.0.1 on 2018-03-03 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0003_genesets_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneSetTox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
                ('n_pos', models.IntegerField()),
                ('effect_size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('coef', models.DecimalField(decimal_places=2, max_digits=5)),
                ('p_adj', models.FloatField()),
                ('q_adj', models.FloatField()),
                ('rank', models.IntegerField()),
                ('geneset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tp.GeneSets')),
            ],
        ),
        migrations.CreateModel(
            name='ToxPhenotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='genesettox',
            name='tox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tp.ToxPhenotype'),
        ),
    ]
