# Generated by Django 2.0.1 on 2018-07-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0004_auto_20180303_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='genesets',
            name='repr_set',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='tissue',
            field=models.CharField(choices=[('liver', 'liver'), ('kidney', 'kidney'), ('heart', 'heart'), ('primary_heps', 'primary hepatocytes')], default='liver', max_length=20),
        ),
    ]
