# Generated by Django 2.0.4 on 2018-11-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0005_auto_20180717_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='experiment_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='foldchangeresult',
            name='expression_ctl',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_name',
            field=models.CharField(max_length=150),
        ),
    ]
