# Generated by Django 2.0.1 on 2018-08-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0005_auto_20180717_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_name',
            field=models.CharField(max_length=150),
        ),
    ]
