# Generated by Django 2.0.4 on 2018-11-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0006_auto_20181106_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='order',
        ),
    ]
