# Generated by Django 2.0.1 on 2018-11-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0006_auto_20180814_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='ensembl_rn6',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='experiment_name',
            field=models.CharField(max_length=500),
        ),
    ]
