# Generated by Django 2.1.5 on 2019-05-10 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0007_auto_20190315_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentVsToxPhenotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.BooleanField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tp.Experiment')),
                ('tox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tp.ToxPhenotype')),
            ],
        ),
    ]
