# Generated by Django 2.0.1 on 2018-11-20 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0007_auto_20181109_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkDoseResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bm2_file', models.CharField(max_length=100)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tp.Experiment')),
            ],
        ),
    ]
