# Generated by Django 2.0.1 on 2018-12-12 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0008_benchmarkdoseresult'),
        ('tp', '0007_remove_sample_order'),
    ]

    operations = [
    ]
