# Generated by Django 2.1.5 on 2019-05-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0008_experimentvstoxphenotype'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentvstoxphenotype',
            name='type',
            field=models.CharField(choices=[('C', 'concurrent'), ('P', 'predictive')], default='C', max_length=1),
        ),
    ]
