# Generated by Django 2.0.1 on 2018-12-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0009_merge_20181212_1932'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BenchmarkDoseResult',
            new_name='BenchmarkDoseFile',
        ),
        migrations.AlterField(
            model_name='study',
            name='permission',
            field=models.CharField(choices=[('S', 'Private'), ('P', 'Public')], default='S', max_length=1, null=True),
        ),
    ]
