# Generated by Django 2.0.1 on 2018-12-12 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0010_auto_20181212_1932'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BenchmarkDoseFile',
            new_name='BMDFile',
        ),
    ]
