# Generated by Django 2.0.1 on 2018-12-12 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0011_auto_20181212_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMDPathwayResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.CharField(max_length=100, verbose_name='Analysis')),
                ('pathway_id', models.CharField(max_length=20, verbose_name='GO/Pathway/Gene Set ID')),
                ('pathway_name', models.CharField(max_length=250, verbose_name='GO/Pathway/Gene Set Name')),
                ('all_genes_data', models.IntegerField(verbose_name='All Genes (Expression Data)')),
                ('all_genes_platform', models.IntegerField(verbose_name='All Genes (Platform)')),
                ('input_genes', models.IntegerField(verbose_name='Input Genes')),
                ('pass_filter_genes', models.IntegerField(verbose_name='Genes That Passed All Filters')),
                ('bmd_median', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='BMD Median')),
                ('bmdl_median', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='BMDL Median')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tp.Experiment')),
            ],
        ),
    ]
