# Generated by Django 2.0.1 on 2018-12-13 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0012_bmdpathwayresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMDAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Analysis')),
                ('experiments', models.ManyToManyField(to='tp.Experiment')),
            ],
        ),
        migrations.RemoveField(
            model_name='bmdpathwayresult',
            name='experiment',
        ),
        migrations.AddField(
            model_name='sample',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bmdpathwayresult',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tp.BMDAnalysis'),
        ),
    ]
