# Generated by Django 2.0.1 on 2018-12-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0013_auto_20181213_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmdanalysis',
            name='barcode',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='bmdanalysis',
            unique_together={('name', 'barcode')},
        ),
    ]
