# Generated by Django 2.0.1 on 2019-01-18 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tp', '0017_auto_20190118_1533'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserGeneBookmark',
            new_name='GeneBookmark',
        ),
        migrations.RenameModel(
            old_name='UserGeneSetBookmark',
            new_name='GeneSetBookmark',
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='user',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='owner',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='type',
            field=models.CharField(choices=[('G', 'genes'), ('GS', 'gene sets')], default='G', max_length=2),
        ),
    ]
